scrape_configs:
  - job_name: "profiles"
    scrape_interval: "15s"
    static_configs:
      - targets: ["profiles:4100"]
  - job_name: "agent"
    scrape_interval: "15s"
    static_configs:
      - targets: ["agent:12345"]
  - job_name: "grafana"
    scrape_interval: "15s"
    static_configs:
      - targets: ["grafana:6060"]