version: '3.9'


# Read-Write mode (Metrics)
services:

  agent:
    depends_on: # https://docs.docker.com/compose/startup-order
      mimir:
        condition: service_healthy
    image: grafana/agent:v0.35.2
    hostname: agent
    restart: always
    volumes:
      - ../../common/config/agent-flow:/etc/agent-config
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - /bin/grafana-agent
      - run
      - /etc/agent-config/read-write-mode-metrics.river # Notics: Agent use read-write-mode-metrics.river
      - --server.http.listen-addr=0.0.0.0:12345
      - --cluster.enabled=true
      - --disable-reporting=true
    environment:
      - AGENT_MODE=flow
      - AGENT_CONFIG_FOLDER=/etc/agent-config
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:12345/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "12345:12345"

  mimir:
    depends_on: # https://docs.docker.com/compose/startup-order
      minio:
        condition: service_healthy
    image: grafana/mimir:2.9.0
    hostname: mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -log.level=info
    volumes:
      - ../../common/config/mimir/read-write-mode-metrics.yaml:/etc/mimir.yaml
      - data-mimir:/data:delegated
    ports:
      - "9009:9009"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9009/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:10.0.3
    hostname: grafana
    command:
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ../../common/config/grafana/grafana.ini:/etc/grafana-config/grafana.ini
      - ../../common/config/grafana/dashboards:/var/lib/grafana/dashboards
      - ../../common/config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_LOG_LEVEL=error
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin_password}
    ports:
      - "3000:3000"

  minio:
    image: minio/minio:RELEASE.2023-07-18T17-49-40Z
    hostname: minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/mimir-data /data/mimir-rules /data/mimir-alertmanager && \
        minio server /data --console-address ':9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin_password
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
      - MINIO_PROMETHEUS_URL="http://mimir:9009/prometheus"
      - MINIO_PROMETHEUS_JOB_ID="integrations/minio"
    volumes:
      - data-minio:/data:delegated
    healthcheck:
      test: ["CMD", "curl","-f","http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9001:9001"

volumes:
  data-mimir:
    driver: local
  data-minio:
    driver: local
