# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

  external_labels:
    scraped_by: prometheus
    cluster: docker-compose
    namespace: monitoring

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - /etc/prometheus/rules.yaml
  - /etc/prometheus/alerts.yaml

remote_write:
  - url: http://mimir:8080/api/v1/push
    remote_timeout: "30s"
    send_exemplars: true
    send_native_histograms: true
    # headers:
    #   X-Scope-OrgID: anonymous

scrape_configs:
  - job_name: monitoring/prometheus
    scrape_classic_histograms: true
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          pod: prometheus
          container: prometheus
  
  - job_name: monitoring/mimir
    scrape_classic_histograms: true
    dns_sd_configs:
      - names:
          - mimir
        type: A
        port: 8080
  
  - job_name: monitoring/minio
    scrape_classic_histograms: true
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']
        labels:
          pod: minio
          container: minio