apiVersion: 1

datasources:
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  uid: loki
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: traceID=(\w+)
        name: TraceID
        url: $${__value.raw}