apiVersion: 1

datasources:
- name: Pyroscope
  type: phlare
  access: proxy
  orgId: 1
  uid: pyroscope
  url: http://pyroscope:4100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true