auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: warn

common:
  compactor_address: loki-backend
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      endpoint: minio:9000
      bucketnames: loki-data
      access_key_id: admin
      secret_access_key: admin_password
      insecure: true
      s3forcepathstyle: true

memberlist:
  join_members: [ loki-memberlist:7946 ]

ingester:
  lifecycler:
    join_after: 10s
    observe_period: 5s
    ring:
      replication_factor: 2
  chunk_idle_period: 1m
  max_chunk_age: 1m
  chunk_retain_period: 30s
  chunk_encoding: snappy
  flush_op_timeout: 10s

ruler:
  storage:
    s3:
      bucketnames: loki-rules

schema_config:
  configs:
    - from: 2023-08-01
      store: tsdb
      object_store: s3
      schema: v12
      index:
        prefix: index_
        period: 24h

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 30m
  split_queries_by_interval: 15m

chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: true

query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true

frontend:
  compress_responses: true

query_scheduler:
  max_outstanding_requests_per_tenant: 1024

compactor:
  working_directory: /tmp/compactor
  shared_store: s3

# -reporting.enabled=false
analytics:
 reporting_enabled: false
