version: '3.9'

# Microservices mode (Metrics)
services:

  agent:
    depends_on:
      distributor:
        condition: service_healthy
    image: grafana/agent:v0.35.2
    volumes:
      - ../../common/config/agent-flow:/etc/agent-config
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - /bin/grafana-agent
      - run
      - /etc/agent-config/microservices-mode-metrics.river # Note: Agent use microservices-mode-metrics.river
      - --server.http.listen-addr=0.0.0.0:12345
      - --cluster.enabled=true
      - --disable-reporting=true
    environment:
      - AGENT_MODE=flow
      - AGENT_CONFIG_FOLDER=/etc/agent-config
    ports:
      - "12345:12345"
    networks:
      - microservices-mode-metrics

  gateway:
    image: nginxinc/nginx-unprivileged:1.25-alpine
    volumes:
      - ../../common/config/nginx:/etc/nginx/templates
      - ../../common/config/mimir/gateway.conf.template:/etc/nginx/templates/gateway.conf.template
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - DISTRIBUTOR_HOST=distributor:8080
      - ALERT_MANAGER_HOST=alertmanager:8080
      - RULER_HOST=ruler:8080
      - QUERY_FRONTEND_HOST=query-frontend:8080
      - COMPACTOR_HOST=compactor:8080
    # ports:
    #   - "8080:8080"
    networks:
      - microservices-mode-metrics

  distributor:
    depends_on:
      ingester:
        condition: service_started
    image: &mimirImage grafana/mimir:2.9.0
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -target=distributor
#      - -log.level=warn
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-mode-metrics

  overrides-exporter:
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -target=overrides-exporter
    networks:
      - microservices-mode-metrics

  querier:
    depends_on:
      query-scheduler:
        condition: service_started
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -target=querier
    networks:
      - microservices-mode-metrics

  query-frontend:
    depends_on:
      query-scheduler:
        condition: service_started
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -target=query-frontend
    networks:
      - microservices-mode-metrics

  query-scheduler:
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -target=query-scheduler
    networks:
      - microservices-mode-metrics

  ruler:
    depends_on:
      minio:
        condition: service_healthy
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -target=ruler
    networks:
      - microservices-mode-metrics

  alertmanager:
    depends_on:
      minio:
        condition: service_healthy
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -target=alertmanager
    networks:
      - microservices-mode-metrics

  compactor:
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -target=compactor
    networks:
      - microservices-mode-metrics

  ingester:
    depends_on:
      minio:
        condition: service_healthy
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -target=ingester
    ports:
      - "8080:8080"
    networks:
      - microservices-mode-metrics

  ingester-2:
    depends_on:
      minio:
        condition: service_healthy
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -target=ingester
    networks:
      - microservices-mode-metrics

  ingester-3:
    depends_on:
      minio:
        condition: service_healthy
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -target=ingester
    networks:
      - microservices-mode-metrics

  store-gateway:
    depends_on:
      minio:
        condition: service_healthy
    image: *mimirImage
    volumes:
      - ../../common/config/mimir/microservices-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use microservices-mode-metrics.yaml
      - ./config/mimir:/etc/mimir
    command:
      - -config.file=/etc/mimir.yaml
      - -target=store-gateway
    networks:
      - microservices-mode-metrics

  grafana:
    image: grafana/grafana:10.0.3
    command:
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ../../common/config/grafana/grafana.ini:/etc/grafana-config/grafana.ini
      - ../../common/config/grafana/dashboards:/var/lib/grafana/dashboards
      - ../../common/config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ../../../monitoring-mixins/mimir-mixin/deploy/dashboards_out:/var/lib/grafana/dashboards/mimir-mixin # load dashboards
    environment:
      - GF_LOG_LEVEL=error
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin_password}
    ports:
      - "3000:3000"
    networks:
      - microservices-mode-metrics

  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/mimir-data /data/mimir-rules /data/mimir-alertmanager && \
        minio server /data --console-address ':9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin_password
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    volumes:
      - data-minio:/data:delegated
    healthcheck:
      test: ["CMD", "curl","-f","http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9001:9001"
    networks:
      - microservices-mode-metrics

networks:
  microservices-mode-metrics:

volumes:
  data-minio:
    driver: local
