# config file version
apiVersion: 1

# List of contact points to import or update
contactPoints:
  # <int> organization ID, default = 1
  - orgId: 1
    # <string, required> name of the contact point
    name: cp_email_wangweifeng
    receivers:
      # <string, required> unique identifier for the receiver
      - uid: cp_email_wangweifeng
        # <string, required> type of the receiver
        type: email
        # <bool, optional> Disable the additional [Incident Resolved] follow-up alert, default = false
        disableResolveMessage: false
        # <object, required> settings for the specific receiver type
        settings:
          addresses: me@example.com;you@example.com
          singleEmail: false
          message: my optional message to include
          subject: |
            {{ template "default.title" . }}
