version: '3.9'


# Monolithic mode (Profiles)
services:

  agent:
    depends_on: # https://docs.docker.com/compose/startup-order
      pyroscope:
        condition: service_started
    image: grafana/agent:v0.35.2
    hostname: agent
    restart: always
    volumes:
      - ../../common/config/agent-flow:/etc/agent-config
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - /bin/grafana-agent
      - run
      - /etc/agent-config/monolithic-mode-profiles.river # Notics: Agent use monolithic-mode-profiles.river
      - --server.http.listen-addr=0.0.0.0:12345
      - --cluster.enabled=true
      - --disable-reporting=true
    environment:
      - AGENT_MODE=flow
      - AGENT_CONFIG_FOLDER=/etc/agent-config
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:12345/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "12345:12345"

  pyroscope:
    image: grafana/phlare:weekly-f22-06e09923
    hostname: pyroscope
    volumes:
      - ../../common/config/pyroscope/monolithic-mode-profiles.yaml:/etc/pyroscope.yaml
    command:
      - -config.file=/etc/pyroscope.yaml
      - -log.level=warn
    ports:
      - "4100:4100"

  grafana:
    image: grafana/grafana:10.0.3
    hostname: grafana
    command:
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ../../common/config/grafana/grafana.ini:/etc/grafana-config/grafana.ini
      - ../../common/config/grafana/dashboards:/var/lib/grafana/dashboards
      - ../../common/config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_LOG_LEVEL=error
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin_password}
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor,pyroscopeFlameGraph
      - GF_DIAGNOSTICS_PROFILING_ENABLED=true
      - GF_DIAGNOSTICS_PROFILING_ADDR=0.0.0.0
      - GF_DIAGNOSTICS_PROFILING_PORT=6060
      # - GF_INSTALL_PLUGINS=pyroscope-datasource,pyroscope-panel
    ports:
      - "3000:3000"

  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    hostname: minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/pyroscope-data && \
        minio server /data --console-address ':9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin_password
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    volumes:
      - data-minio:/data:delegated
    healthcheck:
      test: ["CMD", "curl","-f","http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9001:9001"

volumes:
  data-minio:
    driver: local
