version: '3.9'


# Monolithic mode (Traces)
services:

  agent:
    depends_on:
      tempo:
        condition: service_started
    image: grafana/agent:v0.35.3
    volumes:
      - ../../common/config/agent-flow:/etc/agent-config
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - /bin/grafana-agent
      - run
      - /etc/agent-config/traces.river
      - --server.http.listen-addr=0.0.0.0:12345
      - --cluster.enabled=true
      - --disable-reporting=true
    environment:
      - AGENT_MODE=flow
      - AGENT_CONFIG_FOLDER=/etc/agent-config
    ports:
      - "12345:12345"
    networks:
      - monolithic-mode-traces

  gateway:
    depends_on:
      tempo:
        condition: service_started
    image: nginxinc/nginx-unprivileged:1.25-alpine
    restart: always
    volumes:
      - ../../common/config/nginx:/etc/nginx/templates
      - ../../common/config/tempo/gateway.conf.template:/etc/nginx/templates/gateway_tempo.conf.template
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - DISTRIBUTOR_HOST=tempo
      - INGESTER_HOST=tempo
      - QUERY_FRONTEND_HOST=tempo
      - COMPACTOR_HOST=tempo
    ports:
      - "3200"
      - "4317"
    networks:
      - monolithic-mode-traces

  tempo:
    depends_on:
      minio:
        condition: service_healthy
    image: &tempoImage grafana/tempo:2.2.0
    restart: always
    volumes:
      - ./config/tempo/scalable-single-binary.yaml:/etc/tempo.yaml # Note: Tempo use scalable-single-binary.yaml
    command:
      - -config.file=/etc/tempo.yaml
      - -target=scalable-single-binary
      - -log.level=error
    ports:
      - "3200"
    # Horizontally scale up support(Monolithic mode)
    # https://grafana.com/docs/tempo/latest/setup/deployment/#scaling-monolithic-mode
    deploy:
      replicas: 2
    networks:
      monolithic-mode-traces:
        aliases:
          - tempo-memberlist

  grafana:
    image: grafana/grafana:10.0.3
    command:
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ../../common/config/grafana/grafana.ini:/etc/grafana-config/grafana.ini
      - ../../common/config/grafana/dashboards:/var/lib/grafana/dashboards
      - ../../common/config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_LOG_LEVEL=error
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin_password}
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      - GF_TRACING_OPENTELEMETRY_OTLP_ADDRESS=agent:4317
      - GF_TRACING_OPENTELEMETRY_CUSTOM_ATTRIBUTES=cluster:docker-compose,namespace:monitoring
    ports:
      - "3000:3000"
    networks:
      - monolithic-mode-traces

  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/tempo-data  && \
        minio server /data --console-address ':9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin_password
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    volumes:
      - data-minio:/data:delegated
    healthcheck:
      test: ["CMD", "curl","-f","http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9001:9001"
    networks:
      - monolithic-mode-traces

networks:
  monolithic-mode-traces:

volumes:
  data-minio:
    driver: local
