# Do not use this configuration in production.
# It is for demonstration purposes only.
multitenancy_enabled: false

# -usage-stats.enabled=false
usage_stats:
  enabled: false

server:
  http_listen_port: 9009

common:
  storage:
    backend: s3
    s3:
      endpoint:          minio:9000
      access_key_id:     admin
      secret_access_key: admin_password
      insecure:          true

blocks_storage:
  s3:
    bucket_name: mimir-data
  tsdb:
    dir: /data/ingester

  bucket_store:
    index_cache:
      backend: memcached
      memcached:
        addresses: dns+memcached:11211

    chunks_cache:
      backend: memcached
      memcached:
        addresses: dns+memcached:11211

    metadata_cache:
      backend: memcached
      memcached:
        addresses: dns+memcached:11211


memberlist:
  # Use write replicas as seed nodes.
  join_members: [ mimir-write-1, mimir-write-2 ]

ruler:
  rule_path: /data/rules
  # Each ruler is configured to route alerts to the Alertmanager running within the same component.
  alertmanager_url: http://localhost:8080/alertmanager

ruler_storage:
  s3:
    bucket_name: mimir-rules
  cache:
    backend: memcached
    memcached:
      addresses: dns+memcached:11211

query_scheduler:
  service_discovery_mode: "ring"

alertmanager:
  data_dir: /data/alertmanager
  fallback_config_file: /etc/mimir/alertmanager-fallback-config.yaml
  external_url: http://localhost:8006/alertmanager

alertmanager_storage:
  s3:
    bucket_name: mimir-alertmanager

overrides_exporter:
  ring:
    enabled: true
    wait_stability_min_duration: 30s

limits:
  native_histograms_ingestion_enabled: true

runtime_config:
  file: /etc/mimir/runtime.yaml
