# Do not use this configuration in production.
# It is for demonstration purposes only.
multitenancy_enabled: false

# -usage-stats.enabled=false
usage_stats:
  enabled: false

common:
  storage:
    backend: s3
    s3:
      endpoint:          minio:9000
      access_key_id:     admin
      secret_access_key: admin_password
      insecure:          true

blocks_storage:
  s3:
    bucket_name: mimir-data
  tsdb:
    dir: /data/tsdb

compactor:
  data_dir: /tmp/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

ruler:
  rule_path: /data/ruler
  alertmanager_url: http://localhost:9009/alertmanager

ruler_storage:
  s3:
    bucket_name: mimir-ruler

alertmanager:
  data_dir: /data/alertmanager
  external_url: http://localhost:9009/alertmanager

alertmanager_storage:
  s3:
    bucket_name: mimir-alertmanager

server:
  http_listen_port: 9009
  log_level: error

store_gateway:
  sharding_ring:
    replication_factor: 1

limits:
  native_histograms_ingestion_enabled: true