apiVersion: 1

datasources:
- name: Traces
  type: tempo
  access: proxy
  orgId: 1
  uid: traces
  url: http://gateway:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  apiVersion: 1