name: ci
on:
  push:
    branches: [main]
    paths:
    - 'monitoring-mixins/**'
    - '**.go'
    - go.mod
    - go.sum

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - uses: actions/checkout@v3
    - name: Run Dagger pipeline
      run: go run ci/main.go